### ISSUE TITLE
API Blocked

### ISSUE THREAD

**Issue by DanielBarnett714** [DanielBarnett714/AddressToGPS#1]
Well google seems to have blocked their API for this app. I'm currently trying to figure out a way to fix it but I don't know if I will be able to. It seems to be tied with the package name, so the code is still functional, but the app doesn't work. Any help would be greatly appreciated as I think this is a very useful app.

Daniel

**Comment by ghost** [comment]
While I cannot point to a specific location, most likely the openstreetmap and opendata communities have some geocoding data available. There might even be some data available for offline usage, since I remember working on such stuff ages ago...

**Comment by DanielBarnett714** [comment]
Turns out google blocked all local_storage from android access to the api. So I spent some money and am now hosting addresstogps.com with a Maps API key, and the app now uses that site.
