### ISSUE TITLE
F-droid availability

### ISSUE THREAD

**Issue by mrjovanovic** [DanielBarnett714/AddressToGPS#4]
Any chance of getting this app on F-droid? :)

**Comment by DanielBarnett714** [comment]
Working on it right now!

**Comment by mrjovanovic** [comment]
Thanks, that's amazing. :)

**Comment by ghost** [comment]
Should be building tonight/tomorrow. Further updates are currently blocked by https://github.com/DanielBarnett714/AddressToGPS/issues/5 but that is a minor issue that is easily fixed.
