### ISSUE TITLE
Mismatching version information

### ISSUE THREAD

**Issue by ghost** [DanielBarnett714/AddressToGPS#5]
`./app/build.gradle` and `./app/src/main/AndroidManifest.xml` have different version information. Please raise them to the same level or -- what I personally recommend -- just drop them in one place.

**Comment by DanielBarnett714** [comment]
I fixed the build.gradle, or at least I think I did. Hopefully it works now

**Comment by DanielBarnett714** [comment]
I still can't figure out why the Format isn't working correctly.
