### ISSUE TITLE
Search OpenStreetMap first

### ISSUE THREAD

**Issue by ghost** [DanielBarnett714/AddressToGPS#6]
I think Google should be used as a fall-back method if the address is not already in OpenStreetMap. [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) is a well-used geocoder, and the MapQuest [instance](https://open.mapquestapi.com/nominatim/) is acceptable for heavy use.

[Mapzen Search](https://mapzen.com/projects/search/) is another possibility.

**Comment by DanielBarnett714** [comment]
I've finally gotten a chance to look into mapzen and it is very cool. I think that will probably my next goal. I'll have to incorporate some kind of poi lookup if I do though. I wonder if there are any other point of interest api's that are open.

**Comment by DanielBarnett714** [comment]
Closing this issue now that I've released https://github.com/DanielBarnett714/Acastus
