### ISSUE TITLE
Encourage users to map addresses in OSM

### ISSUE THREAD

**Issue by ghost** [DanielBarnett714/AddressToGPS#7]
Hopefully your app will become obsolete if OSM data improves. Once users have used your app and arrived at their destination, they should be able to verify the address and add it to OSM. However, we should be clear not to copy from Google.

This is a general idea and I will try to think of specific ways this can be implemented. Is this something you would be interested in?

**Comment by DanielBarnett714** [comment]
I am interested but I agree, using google to update OSM data might be skirting the line. I don't want the API blocked

**Comment by ghost** [comment]
It wouldn't need to use Google at all. Just a reminder to use an editor like [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) once you got to the destination and do a survey.

Although a kind of geo-notification would require more permissions and may fall outside the scope of what you want to do. My point is if the address doesn't yet exist in OSM, we should make it simple for users to add the address when they are in a position to survey it. That way we improve the map and help to solve the problem instead of relying on Google. There should be no reason to use this app for the same location twice.
